services:
  hubly-db:
    container_name: hubly-db
    image: postgres:16
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=hublypass
      - POSTGRES_DB=hubly_db
    networks:
      - db-net # Rede isolada
    volumes:
      - hubly-db-data:/var/lib/postgresql/data # Volume do tipo NAMED

  hubly-api:
    container_name: hubly-api
    build:
      context: ./code/api
      dockerfile: Hubly.Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=hubly-db;Database=hubly_db;Username=admin;Password=hublypass
    volumes:
      - ./code/api:/app # Volume do tipo BIND MOUNT (Hot Reload)
    depends_on:
      - hubly-db
    networks:
      - app-net 
      - db-net  

  hubly-web:
    container_name: hubly-web
    image: node:20
    working_dir: /app
    volumes:
      - ./code/web:/app # Volume do tipo BIND MOUNT
      - /app/node_modules # Evita conflitos de dependências entre Windows/Linux
    networks:
      - app-net
    command: npm run dev -- --host

  hubly-nginx:
    container_name: hubly-nginx
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf:ro # Volume do tipo BIND MOUNT
    depends_on:
      - hubly-api
      - hubly-web
    networks:
      - app-net

networks:
  app-net: # Rede para o tráfego Web
    driver: bridge
  db-net:  # Rede privada para dados
    driver: bridge

volumes:
  hubly-db-data: # Definição do volume NAMED