services:
  hubly-db:
    container_name: hubly-db
    image: postgres:16
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=hublypass
      - POSTGRES_DB=hubly_db
    ports:
      - "5432:5432"
    networks:
      - hubly-network
    volumes:
      - hubly-db-data:/var/lib/postgresql/data

  hubly-api:
    container_name: hubly-api
    build:
      context: ./code/api
      dockerfile: Hubly.Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=hubly-db;Database=hubly_db;Username=admin;Password=hublypass
    ports:
      - "5000:8080"
    volumes:
      - ./code/api:/app
    depends_on:
      - hubly-db
    networks:
      - hubly-network

  hubly-web:
    container_name: hubly-web
    image: node:20
    working_dir: /app
    volumes:
      - ./code/web:/app
      - /app/node_modules # Anonymous volume para n√£o misturar OS
    ports:
      - "5173:5173"
    command: npm run dev -- --host
    networks:
      - hubly-network

  hubly-nginx:
    container_name: hubly-nginx
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - hubly-api
      - hubly-web
    networks:
      - hubly-network

networks:
  hubly-network:
    driver: bridge

volumes:
  hubly-db-data: