services:
  hubly-db:
    container_name: hubly-db
    image: postgres:16
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=hublypass
      - POSTGRES_DB=hubly_db
    networks:
      - db-net
    volumes:
      - hubly-db-data:/var/lib/postgresql/data

  hubly-api:
    container_name: hubly-api
    build:
      context: ./code/api
      dockerfile: Dockerfile # Agora o Docker encontra-o logo aqui
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=hubly-db;Database=hubly_db;Username=admin;Password=hublypass
    volumes:
      - ./code/api:/app
    depends_on:
      - hubly-db
    networks:
      - app-net
      - db-net

  hubly-web:
    container_name: hubly-web
    build:
      context: ./code/web
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - ./code/web:/app
      - /app/node_modules
    networks:
      - app-net
    command: npm run dev -- --host

  hubly-nginx:
    container_name: hubly-nginx
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - hubly-api
      - hubly-web
    networks:
      - app-net

networks:
  app-net:
    driver: bridge
  db-net:
    driver: bridge

volumes:
  hubly-db-data: